name: CD

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: AntoineAugusti/trigger-netlify-action@master
        with:
          netlifyHookKey: ${{ secrets.NETLIFY_HOOK_KEY }}
